Task/49 User CRUD has been added
ravenanhq/authmika pull request #23
Opened 2024-03-13 10:13 UTC by jananikuruntham

2024-03-14 08:32 UTC, esakkirajaravenantech requested changes

2024-03-14 08:32 UTC, esakkirajaravenantech commented on front/src/components/User/UserList.tsx
> +  };
```suggestion
  const handleEditSave = async (editedData: RowData) => {
    if ("id" in editedData) {
      editedData.user_name = editedData.userName;
      delete editedData.userName;
      editedData.display_name = editedData.displayName;
      delete editedData.displayName;

      await editUser(editedData.id, editedData);

      handleEditModalClose();
     
      
    }
  };
```

2024-03-14 12:40 UTC, jananikuruntham commented on front/src/components/User/UserList.tsx
> +  };
User CRUD change request has fixed

2024-03-15 12:25 UTC, esakkirajaravenantech approved these changes

2024-03-15 12:25 UTC, merged